#!/usr/bin/env perl

use strict;
use File::Basename;

my @modules = qw(utils ERDB kernel RASTtk);

my $rstr = `git remote -v`;
my($remote) = $rstr =~ /^origin\s+(\S+)/;

my $remote_base = dirname($remote);
print "Check out from $remote_base\n";

chdir('modules') or die "Cannot chdir modules: $!";

for my $mod (@modules)
{
    my $url = "$remote_base/$mod.git";
    print "Clone $url\n";
    my $rc = system("git", "clone", $url);
    if ($rc != 0)
    {
        die "Error cloning $url\n";
    }
}

chdir("..");
print "Bootstrapping SEEDtk\n";
my $rc = system("./bootstrap");
if ($rc != 0)
{
    die "Bootstrap run failed with rc=$rc\n";
}

print "Performing initial build\n";
system("bash", "-c", "source user-env.sh; make");

print "Complete. \n";
print "\nRun the following command to set up your environment:\n\n";
print "source user-env.sh\n";
print "\nTo perform the default directory setup run the following commands\n\n";
print "mkdir Data $ENV{HOME}/public_html/SEEDtk\n";
print "Config --dirs --dna /homes/parrello/DnaRepo Data $ENV{HOME}/public_html/SEEDtk\n";
