=head1 Installing BLAST

=head2 Installing BLAST on Windows

To install BLAST on Windows, download L<ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.2.30+-win64.exe>.
After running the EXE file, run L<Config.pl> to fix up your execution paths.

=head2 Installing BLAST on the Mac

To install BLAST on the Mac, download L<ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.2.30+-universal-macosx.tar.gz>.
Run the L<InstallTool.pl> script specifying the downloaded file as the parameter. This unpacks the tar file into the packages directory.
Run L<Config.pl> to update the directory pointers.

=head2 Installing BLAST on Unix

Use

    curl ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-2.2.30+-x64-linux.tar.gz >blast.tar.gz
    InstallTool blast.tar.gz
    Config
    rm blast.tar.gz


