=head1 Installing SPAdes

SPAdes is the metagenome assembly product that seems to produce the best results. Currently, it is only
available for Linux and MAC. The user manual is available online 
L<http://spades.bioinf.spbau.ru/release3.7.1/manual.html|here>.

=head2 Installing SPAdes on the Mac


Navigate to the C<packages> subdirectory of the SEEDtk project directory and run the following commands.

    curl http://spades.bioinf.spbau.ru/release3.7.1/SPAdes-3.7.1-Darwin.tar.gz -o SPAdes-3.7.1-Darwin.tar.gz
    tar -zxf SPAdes-3.7.1-Darwin.tar.gz

You will want to add the C</SPAdes-3.7.1-Darwin/bin/> subdirectory of C<packages> to the C<tools> list in
your L<FIG_Config>. This puts SPAdes in the tool path. To test your installation, run the L<Config> script to
reconfigure and re-source your environment, then execute

    RunTool spades.py --test

=head2 Installing SPAdes on Unix

Navigate to the C<packages> subdirectory of the SEEDtk project directory and run the following commands.

    curl http://spades.bioinf.spbau.ru/release3.7.1/SPAdes-3.7.1-Linux.tar.gz -o SPAdes-3.7.1-Linux.tar.gz
    tar -zxf SPAdes-3.7.1-Linux.tar.gz

You will want to add the C</SPAdes-3.7.1-Linux/bin/> subdirectory of C<packages> to the C<tools> list in
your L<FIG_Config>. This puts SPAdes in the tool path. To test your installation, run the L<Config> script to
reconfigure and re-source your environment, then execute

    RunTool spades.py --test

