=head1 Installing BLAST

=head2 Installing BLAST on Windows

To install BLAST on Windows, download B<ncbi-blast-#.#.##+-win64.exe>, where I<#.#.##> indicates the current version number,
from L<ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/>. After running the EXE file, run L<Config.pl> to fix
up your execution paths.

=head2 Installing BLAST on the Mac

To install BLAST on the Mac, download B<ncbi-blase-#.#.##+-universal-macosx.tar.gz>, where I<#.#.##> indicates the current
version number, from L<ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/>. Double-clicking this file in your
downloads directory willAfter running the EXE file, run L<Config.pl> to fix
up your execution paths.

